apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube 
    spec:
      containers:
      - name: kube
        imagePullPolicy: Never
        image: app:latest
        ports:
        - containerPort: 80
      

---
apiVersion: v1
kind: Service
metadata:
  name: kube
spec:
  selector:
    app: kube
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 80 
